services:
  web-server:
    build:
      dockerfile: body_problem_web_app/docker/web-server-dev/Dockerfile
      context: ../
    ports:
      - "8000:8000"
    volumes:
      - ../:/srv/app
      - /dev/null:/srv/app/docker-compose-dev.yml
      - /dev/null:/srv/app/docker-compose-prod.yml
      - /srv/app/body_problem_web_app/node_modules/
      - /srv/app/body_problem_web_app/dist/
      - /srv/app/.git/
      - /srv/app/debug/
      - /srv/app/target/
